var ElandTracker=ElandTracker||{};ElandTracker.storageAvailable=function(a){var c;try{if(c=window[a],!c)return!1}catch(e){return!1}try{return c.setItem("__storage_test__","__storage_test__"),c.removeItem("__storage_test__"),!0}catch(d){return!1}};
ElandTracker.setCampaignCodes=function(a){if("undefined"!==typeof a&&ElandTracker.storageAvailable("sessionStorage"))try{a.utmSource&&(this.elandUtmSource=a.utmSource,sessionStorage.setItem("elandUtmSource",this.elandUtmSource)),a.adId&&(this.elandAdId=a.adId,sessionStorage.setItem("elandAdId",this.elandAdId))}catch(c){}};
ElandTracker.getCampaignCodeFromStorage=function(a){if("undefined"===typeof a||!ElandTracker.storageAvailable("sessionStorage"))return"";try{var c=sessionStorage.getItem(a);return c?c:""}catch(e){return""}};
ElandTracker.SendDataNopd=function(a){this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?a.trackType:"view";this.target=a.targetType?a.targetType:"usual";var c=document.createElement("iframe"),e="",d="",e="view"==this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,f="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)d+="DMP_SR\x3d"+this.dmpSr;else throw f="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(f),Error(f);
if(50>=this.target.length)d+="\x26target\x3d"+this.target;else throw f="[ElandTracker] The length of 'target' is invalid.",console.log(f),Error(f);d+="\x26platform\x3dOthers\x26os\x3dOthers";d+="\x26browser\x3dOthers";d=navigator.cookieEnabled?d+"\x26ce\x3d1":d+"\x26ce\x3d0";a.ecInfo&&a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,d+="\x26member_id\x3d"+this.memberID);a="";a=navigator.userAgent.match(/iPhone|iPad|iPod/i)?"iOS":"Others";"iOS"!==a&&navigator.cookieEnabled||(a=ElandTracker.getFingerPrint(),
d+="\x26fp\x3d"+a);d+="\x26nopd\x3d1";a=document.body;c.setAttribute("src",e+d);c.style.width="0px";c.style.height="0px";c.style.border="0px";c.style.display="none";c.setAttribute("alt","elandTracker");c.setAttribute("title","elandTracker");a.appendChild(c)};
ElandTracker.SendData=function(a){function c(a){var b=new Date;b.setTime(b.getTime()+1E3);var c="expires\x3d"+b.toUTCString();a=a+"\x3d"+b.toDateString()+"; "+c+"; path\x3d/";document.cookie=a}function e(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}function d(a){return a.toLowerCase().replace("\x3e","").replace("\x3c","").replace(";","").replace("script","").replace("alert",
"").replace("img","").replace("frame","").replace("input","").replace("title","").replace("body","")}function f(a,b){var c=a.split("/"),d="";if(4<=c.length)for(var e=0;e<b;e++)if(4==c.length&&0==c[3].length){d="Web-Index";break}else if(c.length>3+e)d+=c[3+e]+"-";else break;else d="Web-Index";return d.split("?")[0]}var g={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},
Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},any:function(){return g.Android()||g.BlackBerry()||g.iOS()||g.Opera()||g.Windows()||g.Puffin()||g.Other()}};if(ElandTracker.commonBooleanSwitcher.isTixcraftTracker){if(e("_eel\x3d"))return;if(e("_eul\x3d")){if(e("_eul\x3d"))return;
c("_eul")}else a.hasOwnProperty("ecInfo")&&a.ecInfo.hasOwnProperty("emailInfo")&&(c("_eel"),c("_eul"));this.dmpSr="tixcraft"}else this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?a.trackType:"view";this.target=a.targetType?a.targetType:"usual";this.subfolderDepth=ElandTracker.commonBooleanSwitcher.isTixcraftTracker?3:a.trackSubfolderDepth?a.trackSubfolderDepth:1;this.url=d(location.href);this.referUrl=d(document.referrer);this.adSrTag=function(){for(var a=location.search.substring(1).split("\x26"),
b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_source"==c[0]&&2==c.length)return c[1]}return ElandTracker.getCampaignCodeFromStorage("elandUtmSource")}();this.adIdTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("ad_id"==c[0]&&2==c.length)return c[1]}return ElandTracker.getCampaignCodeFromStorage("elandAdId")}();""!==this.adSrTag&&""!==this.adIdTag&&(this.campaignCodes={},this.campaignCodes.utmSource=this.adSrTag,this.campaignCodes.adId=
this.adIdTag,ElandTracker.setCampaignCodes(this.campaignCodes));this.os=navigator.userAgent.match(/Windows Phone/i)?"WindowsPhone":navigator.userAgent.match(/Android/i)?"Android":navigator.userAgent.match(/iPhone|iPad|iPod/i)?"iOS":navigator.userAgent.match(/Windows NT/i)?"Windows":navigator.userAgent.match(/Macintosh/i)?"MacOS":"Others";this.browser=navigator.userAgent.match(/Edge/i)?"Edge":navigator.userAgent.match(/IEMobile/i)?"IEMobile":navigator.userAgent.match(/msie/i)||navigator.userAgent.match(/trident\/7/i)?
"IE":navigator.userAgent.match(/Puffin/i)?"Puffin":navigator.userAgent.match(/Dolfin/i)?"Dolfin":navigator.userAgent.match(/BlackBerry/i)?"BlackBerry":navigator.userAgent.match(/Android/i)?"Android":navigator.userAgent.match(/UCBrowser/i)?"UCBrowser":navigator.userAgent.match(/Vivaldi/i)?"Vivaldi":navigator.userAgent.match(/Chrome/i)&&navigator.userAgent.match(/Safari/i)?"Chrome":navigator.userAgent.match(/Firefox/i)?"Firefox":navigator.userAgent.match(/Opera Mini/i)?"Opera Mini":navigator.userAgent.match(/Opera Mobi/i)?
"Opera Mobi":navigator.userAgent.match(/Opera/i)?"Opera":navigator.userAgent.match(/Chrome|CriOS/i)?"Chrome":navigator.userAgent.match(/Safari/i)?"Safari":"Others";this.platform="";g.any()?this.platform="Mobile":this.platform="PC";this.subDomain=a.subFolder?a.subFolder:f(this.url,this.subfolderDepth);a.session&&(this.session=a.session);var h=document.createElement("iframe");document.createElement("iframe");var l="",b="",l="view"==this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,
k="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)b+="DMP_SR\x3d"+this.dmpSr;else throw k="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(k),Error(k);if(50>=this.target.length)b+="\x26target\x3d"+this.target;else throw k="[ElandTracker] The length of 'target' is invalid.",console.log(k),Error(k);b+="\x26url\x3d"+encodeURIComponent(this.url)+"\x26refer_url\x3d"+encodeURIComponent(this.referUrl);b+="\x26platform\x3d"+this.platform;b+="\x26os\x3d"+this.os;b+="\x26browser\x3d"+this.browser;
b+="\x26subDomain\x3d"+this.subDomain;""!=this.adSrTag&&(b+="\x26adSrTag\x3d"+this.adSrTag);""!=this.adIdTag&&(b+="\x26adIdTag\x3d"+this.adIdTag);b=navigator.cookieEnabled?b+"\x26ce\x3d1":b+"\x26ce\x3d0";this.session&&(b+="\x26session\x3d"+this.session);a.adInfo&&(b+="\x26info\x3d",a.adInfo.adSiteId&&(this.adSiteId=a.adInfo.adSiteId,b+=this.adSiteId),b+=",",a.adInfo.adZoneId&&(this.adZoneId=a.adInfo.adZoneId,b+=this.adZoneId),b+=",",a.adInfo.adId&&(this.adId=a.adInfo.adId,b+=this.adId),b+=",",a.adInfo.adBannerId&&
(this.adBannerId=a.adInfo.adBannerId,b+=this.adBannerId));a.ecInfo&&(a.ecInfo.itemName&&(this.itemName=a.ecInfo.itemName,b+="\x26item_name\x3d"+this.itemName),a.ecInfo.itemID&&(this.itemID=a.ecInfo.itemID,b+="\x26item_id\x3d"+this.itemID),a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,b+="\x26member_id\x3d"+this.memberID),a.ecInfo.emailInfo&&(this.emailInfo=a.ecInfo.emailInfo,b+="\x26email\x3d"+this.emailInfo),a.ecInfo.payMoney&&(this.payMoney=a.ecInfo.payMoney,b+="\x26pay_money\x3d"+this.payMoney),
a.ecInfo.orderItemID&&(this.orderItemID=a.ecInfo.orderItemID,b+="\x26order_item_id\x3d"+this.orderItemID),a.ecInfo.orderItemName&&(this.orderItemName=a.ecInfo.orderItemName,b+="\x26order_item_name\x3d"+this.orderItemName),a.ecInfo.pvsess&&(this.pvsess=a.ecInfo.pvsess,b+="\x26pvsess\x3d"+this.pvsess));a="";"iOS"!==this.os&&navigator.cookieEnabled||(a=ElandTracker.getFingerPrint(),b+="\x26fp\x3d"+a);a=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head;h.setAttribute("src",
l+b);h.style.width="0px";h.style.height="0px";h.style.border="0px";h.style.display="none";h.setAttribute("alt","elandTracker");h.setAttribute("title","elandTracker");a.appendChild(h)};
ElandTracker.FlushData=function(){setTimeout(function(){var a=document.createElement("iframe");a.setAttribute("src",ElandTracker.apiGateways.elandReceiverDataFlush);a.style.width="0px";a.style.height="0px";a.style.border="0px";a.style.display="none";a.setAttribute("alt","elandTracker");a.setAttribute("title","elandTracker");document.body?document.body.appendChild(a):document.head&&document.head.appendChild(a)},1E3)};
ElandTracker.SendError=function(a){navigator&&navigator.userAgent&&(a=a+' ("'+navigator.userAgent+'")');var c=document.createElement("iframe"),e=ElandTracker.apiGateways.elandReceiverView;a="DMP_SR\x3deland-rd4\x26target\x3ddebug\x26error_message\x3d"+a;location&&location.origin&&location.pathname&&(a=a+"\x26url\x3d"+encodeURIComponent(location.origin+location.pathname));c.setAttribute("src",e+a);c.style.width="0px";c.style.height="0px";c.style.border="0px";c.style.display="none";c.setAttribute("alt",
"elandTracker");c.setAttribute("title","elandTracker");document.body?document.body.appendChild(c):document.head&&document.head.appendChild(c)};ElandTracker.ready&&ElandTracker.ready();