var ElandTracker=ElandTracker||{};ElandTracker.storageAvailable=function(a){var d;try{if(d=window[a],!d)return!1}catch(g){return!1}try{return d.setItem("__storage_test__","__storage_test__"),d.removeItem("__storage_test__"),!0}catch(g){return!1}};
ElandTracker.setCampaignCodes=function(a){if("undefined"!==typeof a&&ElandTracker.storageAvailable("sessionStorage"))try{a.utmSource&&(this.elandUtmSource=a.utmSource,sessionStorage.setItem("elandUtmSource",this.elandUtmSource)),a.adId&&(this.elandAdId=a.adId,sessionStorage.setItem("elandAdId",this.elandAdId))}catch(d){}};
ElandTracker.getCampaignCodeFromStorage=function(a){if("undefined"===typeof a||!ElandTracker.storageAvailable("sessionStorage"))return"";try{var d=sessionStorage.getItem(a);return d?d:""}catch(g){return""}};
ElandTracker.SendDataNopd=function(a){var d={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},
any:function(){return d.Android()||d.BlackBerry()||d.iOS()||d.Opera()||d.Windows()||d.Puffin()||d.Other()}};this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?a.trackType:"view";this.target=a.targetType?a.targetType:"usual";a.subFolder&&(this.subDomain=a.subFolder);var g=document.createElement("iframe"),h="",c="",h="view"===this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,e="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)c+=
"DMP_SR\x3d"+this.dmpSr;else throw e="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(e),Error(e);if(50>=this.target.length)c+="\x26target\x3d"+this.target;else throw e="[ElandTracker] The length of 'target' is invalid.",console.log(e),Error(e);this.platform="";d.any()?this.platform="Mobile":this.platform="PC";c+="\x26platform\x3dOthers\x26os\x3dOthers";c+="\x26browser\x3dOthers";c+="\x26subDomain\x3d"+this.subDomain;c=navigator.cookieEnabled?c+"\x26ce\x3d1":c+"\x26ce\x3d0";a.ecInfo&&
a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,c+="\x26member_id\x3d"+this.memberID);a=function(a){return a.match(/iPhone|iPad|iPod/i)?"iOS":a.match(/Android/i)?"Android":"Others"}(navigator.userAgent);ElandTracker.getFingerPrintV4&&(c="Android"===a||"iOS"===a?c+"\x26fp\x3d":c+"\x26fp2\x3d",c+=ElandTracker.getFingerPrintV4+"\x26nopd\x3d1\x26",a=document.body,g.setAttribute("src",h+c),g.style.width="0px",g.style.height="0px",g.style.border="0px",g.style.display="none",g.setAttribute("alt","elandTracker"),
g.setAttribute("title","elandTracker"),a.appendChild(g))};
ElandTracker.SendData=function(a){function d(a){var b=new Date;b.setTime(b.getTime()+1E3);var c="expires\x3d"+b.toUTCString();a=a+"\x3d"+b.toDateString()+"; "+c+"; path\x3d/";document.cookie=a}function g(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var f=b[c];if(1<f.length)for(;" "===f.charAt(0);)f=f.substring(1);if(0===f.indexOf(a))return f.substring(a.length,f.length)}return""}function h(a,b){var c=a.split("/"),f="";if(4<=c.length)for(var d=0;d<b;d++)if(4===c.length&&0===c[3].length){f=
"Web-Index";break}else if(c.length>3+d)f+=c[3+d]+"-";else break;else f="Web-Index";return f=f.split("?")[0]}var c={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},
Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},any:function(){return c.Android()||c.BlackBerry()||c.iOS()||c.Opera()||c.Windows()||c.Puffin()||c.Other()}};if(ElandTracker.commonBooleanSwitcher.isTixcraftTracker){if(g("_eel\x3d"))return;if(g("_eul\x3d")){if(g("_eul\x3d"))return;d("_eul")}else a.hasOwnProperty("ecInfo")&&a.ecInfo.hasOwnProperty("emailInfo")&&(d("_eel"),d("_eul"));this.dmpSr="tixcraft"}else this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?
a.trackType:"view";this.target=a.targetType?a.targetType:"usual";this.subfolderDepth=ElandTracker.commonBooleanSwitcher.isTixcraftTracker?3:a.trackSubfolderDepth?a.trackSubfolderDepth:1;this.url=a.url?a.url:location.href;this.referUrl=a.referUrl?a.referUrl:document.referrer;this.adSrTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_source"===c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return ElandTracker.getCampaignCodeFromStorage("elandUtmSource")}();
this.adIdTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("ad_id"===c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return ElandTracker.getCampaignCodeFromStorage("elandAdId")}();""!==this.adSrTag&&""!==this.adIdTag&&(this.campaignCodes={},this.campaignCodes.utmSource=this.adSrTag,this.campaignCodes.adId=this.adIdTag,ElandTracker.setCampaignCodes(this.campaignCodes));this.adMediumTag=function(){for(var a=location.search.substring(1).split("\x26"),
b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_medium"===c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return""}();this.adCampaignTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_campaign"===c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return""}();this.adTermTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_term"===
c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return""}();this.adContentTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_content"===c[0])try{return decodeURIComponent(c[1])}catch(f){return c[1]}}return""}();this.os=function(a){return a.match(/Windows Phone/i)?"WindowsPhone":a.match(/Android/i)?"Android":a.match(/iPhone|iPad|iPod/i)?"iOS":a.match(/Windows NT/i)?"Windows":a.match(/Macintosh/i)?"MacOS":"Others"}(navigator.userAgent);
this.browser=function(a){return a.match(/Edge/i)?"Edge":a.match(/IEMobile/i)?"IEMobile":a.match(/msie/i)||a.match(/trident\/7/i)?"IE":a.match(/Puffin/i)?"Puffin":a.match(/Dolfin/i)?"Dolfin":a.match(/BlackBerry/i)?"BlackBerry":a.match(/Android/i)?"Android":a.match(/UCBrowser/i)?"UCBrowser":a.match(/Vivaldi/i)?"Vivaldi":a.match(/Chrome/i)&&a.match(/Safari/i)?"Chrome":a.match(/Firefox/i)?"Firefox":a.match(/Opera Mini/i)?"Opera Mini":a.match(/Opera Mobi/i)?"Opera Mobi":a.match(/Opera/i)?"Opera":a.match(/Chrome|CriOS/i)?
"Chrome":a.match(/Safari/i)?"Safari":"Others"}(navigator.userAgent);this.platform="";c.any()?this.platform="Mobile":this.platform="PC";this.subDomain=a.subFolder?a.subFolder:h(this.url,this.subfolderDepth);a.session&&(this.session=a.session);var e=document.createElement("iframe");document.createElement("iframe");var f="",b="",f="view"==this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,k="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)b+="DMP_SR\x3d"+
this.dmpSr;else throw k="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(k),Error(k);if(50>=this.target.length)b+="\x26target\x3d"+this.target;else throw k="[ElandTracker] The length of 'target' is invalid.",console.log(k),Error(k);b+="\x26url\x3d"+encodeURIComponent(this.url)+"\x26refer_url\x3d"+encodeURIComponent(this.referUrl);b+="\x26platform\x3d"+this.platform;b+="\x26os\x3d"+this.os;b+="\x26browser\x3d"+this.browser;b+="\x26subDomain\x3d"+this.subDomain;""!==this.adSrTag&&(b+=
"\x26adSrTag\x3d"+this.adSrTag);""!==this.adIdTag&&(b+="\x26adIdTag\x3d"+this.adIdTag);""!==this.adMediumTag&&(b+="\x26adMediumTag\x3d"+this.adMediumTag);""!==this.adCampaignTag&&(b+="\x26adCampaignTag\x3d"+this.adCampaignTag);""!==this.adTermTag&&(b+="\x26adTermTag\x3d"+this.adTermTag);""!==this.adContentTag&&(b+="\x26adContentTag\x3d"+this.adContentTag);b=navigator.cookieEnabled?b+"\x26ce\x3d1":b+"\x26ce\x3d0";this.session&&(b+="\x26session\x3d"+this.session);a.adInfo&&(b+="\x26info\x3d",a.adInfo.adSiteId&&
(this.adSiteId=a.adInfo.adSiteId,b+=this.adSiteId),b+=",",a.adInfo.adZoneId&&(this.adZoneId=a.adInfo.adZoneId,b+=this.adZoneId),b+=",",a.adInfo.adId&&(this.adId=a.adInfo.adId,b+=this.adId),b+=",",a.adInfo.adBannerId&&(this.adBannerId=a.adInfo.adBannerId,b+=this.adBannerId));a.ecInfo&&(a.ecInfo.itemName&&(this.itemName=a.ecInfo.itemName,b+="\x26item_name\x3d"+this.itemName),a.ecInfo.itemID&&(this.itemID=a.ecInfo.itemID,b+="\x26item_id\x3d"+this.itemID),a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,
b+="\x26member_id\x3d"+this.memberID),a.ecInfo.emailInfo&&(this.emailInfo=a.ecInfo.emailInfo,b+="\x26email\x3d"+this.emailInfo),a.ecInfo.payMoney&&(this.payMoney=a.ecInfo.payMoney,b+="\x26pay_money\x3d"+this.payMoney),a.ecInfo.orderItemID&&(this.orderItemID=a.ecInfo.orderItemID,b+="\x26order_item_id\x3d"+this.orderItemID),a.ecInfo.orderItemName&&(this.orderItemName=a.ecInfo.orderItemName,b+="\x26order_item_name\x3d"+this.orderItemName),a.ecInfo.pvsess&&(this.pvsess=a.ecInfo.pvsess,b+="\x26pvsess\x3d"+
this.pvsess));a.idMapping&&a.idMapping.googleId&&(this.googleId=a.idMapping.googleId,b+="\x26gid\x3d"+this.googleId);ElandTracker.getFingerPrintV4&&(b="Android"===this.os||"iOS"===this.os?b+"\x26fp\x3d":b+"\x26fp2\x3d",b+=ElandTracker.getFingerPrintV4+"\x26",a=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head,e.setAttribute("src",f+b),e.style.width="0px",e.style.height="0px",e.style.border="0px",e.style.display="none",e.setAttribute("alt","elandTracker"),e.setAttribute("title",
"elandTracker"),a.appendChild(e))};
ElandTracker.ClickforceSendData=function(a){function d(a,b){var c=a.split("/"),d="";if(4<=c.length)for(var e=0;e<b;e++)if(4===c.length&&0===c[3].length){d="Web-Index";break}else if(c.length>3+e)d+=c[3+e]+"-";else break;else d="Web-Index";return d=d.split("?")[0]}function g(a){return a.toLowerCase().replace("\x3e","").replace("\x3c","").replace(";","").replace("script","").replace("alert","").replace("img","").replace("frame","").replace("input","").replace("title","").replace("body","")}var h={Android:function(){return navigator.userAgent.match(/Android/i)},
BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},any:function(){return h.Android()||h.BlackBerry()||h.iOS()||h.Opera()||h.Windows()||h.Puffin()||
h.Other()}};this.subfolderDepth=a.trackSubfolderDepth?a.trackSubfolderDepth:1;this.target=a.targetType?a.targetType:"ad";this.url=a.url?a.url:g(location.href);this.referUrl=a.referUrl?a.referUrl:g(document.referrer);this.adSrTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("AD_SR"==c[0]||"ad_sr"==c[0])return c[1]}return""}();a.cf_uid&&(this.cf_uid=a.cf_uid);for(var c=a.sp_variable.split(","),e=0;e<c.length&&4>e;e++)null!=this.info?
(this.info+=",",this.info+=c[e]):this.info=c[e];this.dmpSr=a.source?a.source:location.hostname;if(50<this.dmpSr.length&&0>=this.dmpSr.length)throw c="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(c),Error(c);this.trackType=a.trackType?a.trackType:"view";this.os=function(a){return a.match(/Windows Phone/i)?"WindowsPhone":a.match(/Android/i)?"Android":a.match(/iPhone|iPad|iPod/i)?"iOS":a.match(/Windows NT/i)?"Windows":a.match(/Macintosh/i)?"MacOS":"Others"}(navigator.userAgent);this.browser=
function(a){return a.match(/Edge/i)?"Edge":a.match(/IEMobile/i)?"IEMobile":a.match(/msie/i)||a.match(/trident\/7/i)?"IE":a.match(/Puffin/i)?"Puffin":a.match(/Dolfin/i)?"Dolfin":a.match(/BlackBerry/i)?"BlackBerry":a.match(/Android/i)?"Android":a.match(/UCBrowser/i)?"UCBrowser":a.match(/Vivaldi/i)?"Vivaldi":a.match(/Chrome/i)&&a.match(/Safari/i)?"Chrome":a.match(/Firefox/i)?"Firefox":a.match(/Opera Mini/i)?"Opera Mini":a.match(/Opera Mobi/i)?"Opera Mobi":a.match(/Opera/i)?"Opera":a.match(/Chrome|CriOS/i)?
"Chrome":a.match(/Safari/i)?"Safari":"Others"}(navigator.userAgent);this.platform="";h.any()?this.platform="Mobile":this.platform="PC";this.subDomain=a.subFolder?a.subFolder:d(this.url,this.subfolderDepth);c=a="";a="view"==this.trackType?a+"?google_nid\x3dclickforce_dmp\x26google_cm\x26log_type\x3dview":a+"?google_nid\x3dclickforce_dmp\x26google_cm\x26log_type\x3dclick";a+="\x26DMP_SR\x3d"+this.dmpSr;a+="\x26url\x3d"+encodeURIComponent(this.url)+"\x26refer_url\x3d"+encodeURIComponent(this.referUrl);
a+="\x26platform\x3d"+this.platform;a+="\x26os\x3d"+this.os;a+="\x26browser\x3d"+this.browser;a+="\x26subDomain\x3d"+this.subDomain;a+="\x26info\x3d"+this.info;a+="\x26cf_uid\x3d"+this.cf_uid;""!==this.adSrTag&&(a+="\x26adSrTag\x3d"+this.adSrTag);if(50>=this.target.length)a+="\x26target\x3d"+this.target;else throw c="[ElandTracker] The length of 'target' is invalid.",console.log(c),Error(c);a=navigator.cookieEnabled?a+"\x26ce\x3d1":a+"\x26ce\x3d0";c=document.createElement("iframe");ElandTracker.getFingerPrintV4&&
(a="Android"===this.os||"iOS"===this.os?a+"\x26fp\x3d":a+"\x26fp2\x3d",a+=ElandTracker.getFingerPrintV4+"\x26",e=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head,c.setAttribute("src","https://cm.g.doubleclick.net/pixel"+a),c.style.width="0px",c.style.height="0px",c.style.border="0px",c.style.display="none",c.setAttribute("alt","elandTracker"),c.setAttribute("title","elandTracker"),e.appendChild(c))};
ElandTracker.FlushData=function(){setTimeout(function(){var a=document.createElement("iframe");a.setAttribute("src",ElandTracker.apiGateways.elandReceiverDataFlush);a.style.width="0px";a.style.height="0px";a.style.border="0px";a.style.display="none";a.setAttribute("alt","elandTracker");a.setAttribute("title","elandTracker");document.body?document.body.appendChild(a):document.head&&document.head.appendChild(a)},1E3)};
ElandTracker.SendError=function(a){navigator&&navigator.userAgent&&(a=a+' ("'+navigator.userAgent+'")');var d=document.createElement("iframe"),g=ElandTracker.apiGateways.elandReceiverView;a="DMP_SR\x3deland-rd4\x26target\x3ddebug\x26error_message\x3d"+a;location&&location.origin&&location.pathname&&(a=a+"\x26url\x3d"+encodeURIComponent(location.origin+location.pathname));d.setAttribute("src",g+a);d.style.width="0px";d.style.height="0px";d.style.border="0px";d.style.display="none";d.setAttribute("alt",
"elandTracker");d.setAttribute("title","elandTracker");document.body?document.body.appendChild(d):document.head&&document.head.appendChild(d)};ElandTracker.ready&&ElandTracker.ready();