var ElandTracker=ElandTracker||{};ElandTracker.storageAvailable=function(a){var c;try{if(c=window[a],!c)return!1}catch(g){return!1}try{return c.setItem("__storage_test__","__storage_test__"),c.removeItem("__storage_test__"),!0}catch(g){return!1}};
ElandTracker.setCampaignCodes=function(a){if("undefined"!==typeof a&&ElandTracker.storageAvailable("sessionStorage"))try{a.utmSource&&(this.elandUtmSource=a.utmSource,sessionStorage.setItem("elandUtmSource",this.elandUtmSource)),a.adId&&(this.elandAdId=a.adId,sessionStorage.setItem("elandAdId",this.elandAdId))}catch(c){}};
ElandTracker.getCampaignCodeFromStorage=function(a){if("undefined"===typeof a||!ElandTracker.storageAvailable("sessionStorage"))return"";try{var c=sessionStorage.getItem(a);return c?c:""}catch(g){return""}};
ElandTracker.SendData=function(a){function c(a){return a.match(/Edge|edg/i)?"Edge":a.match(/Dalvik/i)?"Android":a.match(/IEMobile/i)?"IEMobile":a.match(/msie|trident\/7/i)?"IE":a.match(/Puffin/i)?"Puffin":a.match(/Dolfin/i)?"Dolfin":a.match(/BlackBerry/i)?"BlackBerry":a.match(/uc\s?browser|\subrowser/i)?"UCBrowser":a.match(/Vivaldi/i)?"Vivaldi":a.match(/Opera|opr/i)?"Opera":a.match(/SamsungBrowser|FB|Instagram|\sline|MiuiBrowser|Baidu|bidubrowser|MicroMessenger/i)||a.match(/wechat|Telegram|Slack|WhatsApp|KAKAOTALK/i)?
"Others":a.match(/mobile Safari/i)&&a.match(/android/i)&&a.match(/version/i)?a.match(/chrome/i)?"Chrome":"Android":a.match(/Chrome/i)&&a.match(/Safari/i)?"Chrome":a.match(/Firefox|FxiOS/i)?"Firefox":a.match(/Opera Mini/i)?"Opera Mini":a.match(/Opera Mobi/i)?"Opera Mobi":a.match(/Chrome|CriOS/i)?"Chrome":a.match(/Safari/i)?"Safari":"Others"}function g(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");if("utm_medium"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return""}
function l(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");if("utm_campaign"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return""}function m(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");if("utm_term"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return""}function n(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");
if("utm_content"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return""}function p(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");if("utm_source"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return ElandTracker.getCampaignCodeFromStorage("elandUtmSource")}function q(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var d=a[b].split("\x3d");if("ad_id"===d[0])try{return decodeURIComponent(d[1])}catch(c){return d[1]}}return ElandTracker.getCampaignCodeFromStorage("elandAdId")}
function r(a,b){var d=a.split("/"),c="";if(4<=d.length)for(var e=0;e<b;e++)if(4===d.length&&0===d[3].length){c="Web-Index";break}else if(d.length>3+e)c+=d[3+e]+"-";else break;else c="Web-Index";return c=c.split("?")[0]}var e={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},
Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},any:function(){return e.Android()||e.BlackBerry()||e.iOS()||e.Opera()||e.Windows()||e.Puffin()||e.Other()}},f=document.createElement("iframe"),b,k="",k=ElandTracker.apiGateways.elandReceiverALL;this.receiveData=a.receiveData?a.receiveData:"0";b="receiveData\x3d"+this.receiveData;this.tno=a.tno?a.tno:"";
b+="\x26tno\x3d"+this.tno;this.callback=a.callback?a.callback:"";b+="\x26callback\x3d"+this.callback;this.trackType="view"==a.trackType?"view":"click";b+="\x26trackType\x3d"+this.trackType;this.os=function(a){return a.match(/Windows Phone/i)?"WindowsPhone":a.match(/Android/i)?"Android":a.match(/iPhone|iPad|iPod/i)?"iOS":a.match(/Windows NT/i)?"Windows":a.match(/Macintosh/i)?"MacOS":"Others"}(navigator.userAgent);this.platform="";e.any()?this.platform="Mobile":this.platform="PC";if("1"==a.receiveData){this.dmpSr=
a.source?a.source:location.hostname;this.url=a.url?a.url:location.href;this.referUrl=a.referUrl?a.referUrl:document.referrer;this.target=a.targetType?a.targetType:"usual";this.subfolderDepth=a.trackSubfolderDepth?a.trackSubfolderDepth:1;this.adSrTag=p();this.adIdTag=q();""!==this.adSrTag&&""!==this.adIdTag&&(this.campaignCodes={},this.campaignCodes.utmSource=this.adSrTag,this.campaignCodes.adId=this.adIdTag,ElandTracker.setCampaignCodes(this.campaignCodes));this.adMediumTag=g();this.adCampaignTag=
l();this.adTermTag=m();this.adContentTag=n();this.browser=c(navigator.userAgent);this.subDomain=a.subFolder?a.subFolder:r(this.url,this.subfolderDepth);a.session&&(this.session=a.session);var h="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)b+="\x26DMP_SR\x3d"+this.dmpSr;else throw h="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(h),Error(h);if(50>=this.target.length)b+="\x26target\x3d"+this.target;else throw h="[ElandTracker] The length of 'target' is invalid.",console.log(h),
Error(h);b+="\x26url\x3d"+encodeURIComponent(this.url)+"\x26refer_url\x3d"+encodeURIComponent(this.referUrl);b+="\x26platform\x3d"+this.platform;b+="\x26os\x3d"+this.os;b+="\x26browser\x3d"+this.browser;b+="\x26subDomain\x3d"+this.subDomain;""!==this.adSrTag&&(b+="\x26adSrTag\x3d"+this.adSrTag);""!==this.adIdTag&&(b+="\x26adIdTag\x3d"+this.adIdTag);""!==this.adMediumTag&&(b+="\x26adMediumTag\x3d"+this.adMediumTag);""!==this.adCampaignTag&&(b+="\x26adCampaignTag\x3d"+this.adCampaignTag);""!==this.adTermTag&&
(b+="\x26adTermTag\x3d"+this.adTermTag);""!==this.adContentTag&&(b+="\x26adContentTag\x3d"+this.adContentTag);b=navigator.cookieEnabled?b+"\x26ce\x3d1":b+"\x26ce\x3d0";this.session&&(b+="\x26session\x3d"+this.session);a.adInfo&&(b+="\x26info\x3d",a.adInfo.adSiteId&&(this.adSiteId=a.adInfo.adSiteId,b+=this.adSiteId),b+=",",a.adInfo.adZoneId&&(this.adZoneId=a.adInfo.adZoneId,b+=this.adZoneId),b+=",",a.adInfo.adId&&(this.adId=a.adInfo.adId,b+=this.adId),b+=",",a.adInfo.adBannerId&&(this.adBannerId=a.adInfo.adBannerId,
b+=this.adBannerId));a.ecInfo&&(a.ecInfo.itemName&&(this.itemName=a.ecInfo.itemName,b+="\x26item_name\x3d"+this.itemName),a.ecInfo.itemID&&(this.itemID=a.ecInfo.itemID,b+="\x26item_id\x3d"+this.itemID),a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,b+="\x26member_id\x3d"+this.memberID),a.ecInfo.emailInfo&&(this.emailInfo=a.ecInfo.emailInfo,b+="\x26email\x3d"+this.emailInfo),a.ecInfo.payMoney&&(this.payMoney=a.ecInfo.payMoney,b+="\x26pay_money\x3d"+this.payMoney),a.ecInfo.orderItemID&&(this.orderItemID=
a.ecInfo.orderItemID,b+="\x26order_item_id\x3d"+this.orderItemID),a.ecInfo.orderItemName&&(this.orderItemName=a.ecInfo.orderItemName,b+="\x26order_item_name\x3d"+this.orderItemName),a.ecInfo.pvsess&&(this.pvsess=a.ecInfo.pvsess,b+="\x26pvsess\x3d"+this.pvsess));a.idMapping&&a.idMapping.googleId&&(this.googleId=a.idMapping.googleId,b+="\x26gid\x3d"+this.googleId)}ElandTracker.getFingerPrintV4&&(b="Android"===this.os||"iOS"===this.os?b+"\x26fp\x3d":b+"\x26fp2\x3d",b+=ElandTracker.getFingerPrintV4+"\x26",
a=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head,f.setAttribute("src",k+b),f.style.width="0px",f.style.height="0px",f.style.border="0px",f.style.display="none",f.setAttribute("alt","elandTracker"),f.setAttribute("title","elandTracker"),a.appendChild(f))};
ElandTracker.FlushData=function(){setTimeout(function(){var a=document.createElement("iframe");a.setAttribute("src",ElandTracker.apiGateways.elandReceiverDataFlush);a.style.width="0px";a.style.height="0px";a.style.border="0px";a.style.display="none";a.setAttribute("alt","elandTracker");a.setAttribute("title","elandTracker");document.body?document.body.appendChild(a):document.head&&document.head.appendChild(a)},1E3)};
ElandTracker.SendError=function(a){navigator&&navigator.userAgent&&(a=a+' ("'+navigator.userAgent+'")');var c=document.createElement("iframe"),g=ElandTracker.apiGateways.elandReceiverALL;a="DMP_SR\x3deland-rd4\x26target\x3ddebug\x26error_message\x3d"+a;location&&location.origin&&location.pathname&&(a=a+"\x26url\x3d"+encodeURIComponent(location.origin+location.pathname));c.setAttribute("src",g+a);c.style.width="0px";c.style.height="0px";c.style.border="0px";c.style.display="none";c.setAttribute("alt",
"elandTracker");c.setAttribute("title","elandTracker");document.body?document.body.appendChild(c):document.head&&document.head.appendChild(c)};ElandTracker.ready&&ElandTracker.ready();