var ElandTracker=ElandTracker||{};ElandTracker.storageAvailable=function(a){var d;try{if(d=window[a],!d)return!1}catch(f){return!1}try{return d.setItem("__storage_test__","__storage_test__"),d.removeItem("__storage_test__"),!0}catch(g){return!1}};
ElandTracker.setCampaignCodes=function(a){if("undefined"!==typeof a&&ElandTracker.storageAvailable("sessionStorage"))try{a.utmSource&&(this.elandUtmSource=a.utmSource,sessionStorage.setItem("elandUtmSource",this.elandUtmSource)),a.adId&&(this.elandAdId=a.adId,sessionStorage.setItem("elandAdId",this.elandAdId))}catch(d){}};
ElandTracker.getCampaignCodeFromStorage=function(a){if("undefined"===typeof a||!ElandTracker.storageAvailable("sessionStorage"))return"";try{var d=sessionStorage.getItem(a);return d?d:""}catch(f){return""}};
ElandTracker.SendDataNopd=function(a){var d={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},
any:function(){return d.Android()||d.BlackBerry()||d.iOS()||d.Opera()||d.Windows()||d.Puffin()||d.Other()}};this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?a.trackType:"view";this.target=a.targetType?a.targetType:"usual";a.subFolder&&(this.subDomain=a.subFolder);var f=document.createElement("iframe"),g="",c="",g="view"===this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,e="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)c+=
"DMP_SR\x3d"+this.dmpSr;else throw e="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(e),Error(e);if(50>=this.target.length)c+="\x26target\x3d"+this.target;else throw e="[ElandTracker] The length of 'target' is invalid.",console.log(e),Error(e);this.platform="";d.any()?this.platform="Mobile":this.platform="PC";c+="\x26platform\x3dOthers";c+="\x26os\x3dOthers";c+="\x26browser\x3dOthers";c+="\x26subDomain\x3d"+this.subDomain;c=navigator.cookieEnabled?c+"\x26ce\x3d1":c+"\x26ce\x3d0";a.ecInfo&&
a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,c+="\x26member_id\x3d"+this.memberID);a=navigator.userAgent.match(/iPhone|iPad|iPod/i)?"iOS":navigator.userAgent.match(/Android/i)?"Android":"Others";e=e="";"Android"===a&&ElandTracker.getFingerPrintV3?ElandTracker.getFingerPrintV3.get(function(a){c+="\x26fp\x3d"+a;c+="\x26nopd\x3d1";a=document.body;f.setAttribute("src",g+c);f.style.width="0px";f.style.height="0px";f.style.border="0px";f.style.display="none";f.setAttribute("alt","elandTracker");
f.setAttribute("title","elandTracker");a.appendChild(f)}):("iOS"===a&&ElandTracker.getFingerPrint?(e=ElandTracker.getFingerPrint(),c+="\x26fp\x3d"+e):"PC"===this.platform&&ElandTracker.getFingerPrintV2&&(e=ElandTracker.getFingerPrintV2(),c+="\x26fp2\x3d"+e),c+="\x26nopd\x3d1",a=document.body,f.setAttribute("src",g+c),f.style.width="0px",f.style.height="0px",f.style.border="0px",f.style.display="none",f.setAttribute("alt","elandTracker"),f.setAttribute("title","elandTracker"),a.appendChild(f))};
ElandTracker.SendData=function(a){function d(a){var b=new Date;b.setTime(b.getTime()+1E3);var c="expires\x3d"+b.toUTCString();a=a+"\x3d"+b.toDateString()+"; "+c+"; path\x3d/";document.cookie=a}function f(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var d=b[c];if(1<d.length)for(;" "===d.charAt(0);)d=d.substring(1);if(0===d.indexOf(a))return d.substring(a.length,d.length)}return""}function g(a,b){var c=a.split("/"),d="";if(4<=c.length)for(var e=0;e<b;e++)if(4===c.length&&0===c[3].length){d=
"Web-Index";break}else if(c.length>3+e)d+=c[3+e]+"-";else break;else d="Web-Index";return d=d.split("?")[0]}var c={Android:function(){return navigator.userAgent.match(/Android/i)},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i)},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i)},Opera:function(){return navigator.userAgent.match(/Opera Mini|Opera Mobi/i)},Puffin:function(){return navigator.userAgent.match(/Puffin/i)},Windows:function(){return navigator.userAgent.match(/IEMobile/i)},
Other:function(){return navigator.userAgent.match(/Mobile|Tablet/i)},any:function(){return c.Android()||c.BlackBerry()||c.iOS()||c.Opera()||c.Windows()||c.Puffin()||c.Other()}};if(ElandTracker.commonBooleanSwitcher.isTixcraftTracker){if(f("_eel\x3d"))return;if(f("_eul\x3d")){if(f("_eul\x3d"))return;d("_eul")}else a.hasOwnProperty("ecInfo")&&a.ecInfo.hasOwnProperty("emailInfo")&&(d("_eel"),d("_eul"));this.dmpSr="tixcraft"}else this.dmpSr=a.source?a.source:location.hostname;this.trackType=a.trackType?
a.trackType:"view";this.target=a.targetType?a.targetType:"usual";this.subfolderDepth=ElandTracker.commonBooleanSwitcher.isTixcraftTracker?3:a.trackSubfolderDepth?a.trackSubfolderDepth:1;this.url=location.href;this.referUrl=document.referrer;this.adSrTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_source"===c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return ElandTracker.getCampaignCodeFromStorage("elandUtmSource")}();
this.adIdTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("ad_id"===c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return ElandTracker.getCampaignCodeFromStorage("elandAdId")}();""!==this.adSrTag&&""!==this.adIdTag&&(this.campaignCodes={},this.campaignCodes.utmSource=this.adSrTag,this.campaignCodes.adId=this.adIdTag,ElandTracker.setCampaignCodes(this.campaignCodes));this.adMediumTag=function(){for(var a=location.search.substring(1).split("\x26"),
b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_medium"===c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return""}();this.adCampaignTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_campaign"===c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return""}();this.adTermTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_term"===
c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return""}();this.adContentTag=function(){for(var a=location.search.substring(1).split("\x26"),b=0;b<a.length;b++){var c=a[b].split("\x3d");if("utm_content"===c[0])try{return decodeURIComponent(c[1])}catch(d){return c[1]}}return""}();this.os=navigator.userAgent.match(/Windows Phone/i)?"WindowsPhone":navigator.userAgent.match(/Android/i)?"Android":navigator.userAgent.match(/iPhone|iPad|iPod/i)?"iOS":navigator.userAgent.match(/Windows NT/i)?
"Windows":navigator.userAgent.match(/Macintosh/i)?"MacOS":"Others";this.browser=navigator.userAgent.match(/Edge/i)?"Edge":navigator.userAgent.match(/IEMobile/i)?"IEMobile":navigator.userAgent.match(/msie/i)||navigator.userAgent.match(/trident\/7/i)?"IE":navigator.userAgent.match(/Puffin/i)?"Puffin":navigator.userAgent.match(/Dolfin/i)?"Dolfin":navigator.userAgent.match(/BlackBerry/i)?"BlackBerry":navigator.userAgent.match(/Android/i)?"Android":navigator.userAgent.match(/UCBrowser/i)?"UCBrowser":navigator.userAgent.match(/Vivaldi/i)?
"Vivaldi":navigator.userAgent.match(/Chrome/i)&&navigator.userAgent.match(/Safari/i)?"Chrome":navigator.userAgent.match(/Firefox/i)?"Firefox":navigator.userAgent.match(/Opera Mini/i)?"Opera Mini":navigator.userAgent.match(/Opera Mobi/i)?"Opera Mobi":navigator.userAgent.match(/Opera/i)?"Opera":navigator.userAgent.match(/Chrome|CriOS/i)?"Chrome":navigator.userAgent.match(/Safari/i)?"Safari":"Others";this.platform="";c.any()?this.platform="Mobile":this.platform="PC";this.subDomain=a.subFolder?a.subFolder:
g(this.url,this.subfolderDepth);a.session&&(this.session=a.session);var e=document.createElement("iframe");document.createElement("iframe");var k="",b="",k="view"==this.trackType?ElandTracker.apiGateways.elandReceiverView:ElandTracker.apiGateways.elandReceiverClick,h="";if(50>=this.dmpSr.length&&0<this.dmpSr.length)b+="DMP_SR\x3d"+this.dmpSr;else throw h="[ElandTracker] The length of 'DMP_SR' is invalid.",console.log(h),Error(h);if(50>=this.target.length)b+="\x26target\x3d"+this.target;else throw h=
"[ElandTracker] The length of 'target' is invalid.",console.log(h),Error(h);b+="\x26url\x3d"+encodeURIComponent(this.url)+"\x26refer_url\x3d"+encodeURIComponent(this.referUrl);b+="\x26platform\x3d"+this.platform;b+="\x26os\x3d"+this.os;b+="\x26browser\x3d"+this.browser;b+="\x26subDomain\x3d"+this.subDomain;""!==this.adSrTag&&(b+="\x26adSrTag\x3d"+this.adSrTag);""!==this.adIdTag&&(b+="\x26adIdTag\x3d"+this.adIdTag);""!==this.adMediumTag&&(b+="\x26adMediumTag\x3d"+this.adMediumTag);""!==this.adCampaignTag&&
(b+="\x26adCampaignTag\x3d"+this.adCampaignTag);""!==this.adTermTag&&(b+="\x26adTermTag\x3d"+this.adTermTag);""!==this.adContentTag&&(b+="\x26adContentTag\x3d"+this.adContentTag);b=navigator.cookieEnabled?b+"\x26ce\x3d1":b+"\x26ce\x3d0";this.session&&(b+="\x26session\x3d"+this.session);a.adInfo&&(b+="\x26info\x3d",a.adInfo.adSiteId&&(this.adSiteId=a.adInfo.adSiteId,b+=this.adSiteId),b+=",",a.adInfo.adZoneId&&(this.adZoneId=a.adInfo.adZoneId,b+=this.adZoneId),b+=",",a.adInfo.adId&&(this.adId=a.adInfo.adId,
b+=this.adId),b+=",",a.adInfo.adBannerId&&(this.adBannerId=a.adInfo.adBannerId,b+=this.adBannerId));a.ecInfo&&(a.ecInfo.itemName&&(this.itemName=a.ecInfo.itemName,b+="\x26item_name\x3d"+this.itemName),a.ecInfo.itemID&&(this.itemID=a.ecInfo.itemID,b+="\x26item_id\x3d"+this.itemID),a.ecInfo.memberID&&(this.memberID=a.ecInfo.memberID,b+="\x26member_id\x3d"+this.memberID),a.ecInfo.emailInfo&&(this.emailInfo=a.ecInfo.emailInfo,b+="\x26email\x3d"+this.emailInfo),a.ecInfo.payMoney&&(this.payMoney=a.ecInfo.payMoney,
b+="\x26pay_money\x3d"+this.payMoney),a.ecInfo.orderItemID&&(this.orderItemID=a.ecInfo.orderItemID,b+="\x26order_item_id\x3d"+this.orderItemID),a.ecInfo.orderItemName&&(this.orderItemName=a.ecInfo.orderItemName,b+="\x26order_item_name\x3d"+this.orderItemName),a.ecInfo.pvsess&&(this.pvsess=a.ecInfo.pvsess,b+="\x26pvsess\x3d"+this.pvsess));a.idMapping&&a.idMapping.googleId&&(this.googleId=a.idMapping.googleId,b+="\x26gid\x3d"+this.googleId);a=a="";"Android"===this.os&&ElandTracker.getFingerPrintV3?
ElandTracker.getFingerPrintV3.get(function(a){b+="\x26fp\x3d"+a;a=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head;e.setAttribute("src",k+b);e.style.width="0px";e.style.height="0px";e.style.border="0px";e.style.display="none";e.setAttribute("alt","elandTracker");e.setAttribute("title","elandTracker");a.appendChild(e)}):("iOS"===this.os&&ElandTracker.getFingerPrint?(a=ElandTracker.getFingerPrint(),b+="\x26fp\x3d"+a):"PC"===this.platform&&ElandTracker.getFingerPrintV2&&
(a=ElandTracker.getFingerPrintV2(),b+="\x26fp2\x3d"+a),a=ElandTracker.commonBooleanSwitcher.attachIframeToBody?document.body:document.head,e.setAttribute("src",k+b),e.style.width="0px",e.style.height="0px",e.style.border="0px",e.style.display="none",e.setAttribute("alt","elandTracker"),e.setAttribute("title","elandTracker"),a.appendChild(e))};
ElandTracker.FlushData=function(){setTimeout(function(){var a=document.createElement("iframe");a.setAttribute("src",ElandTracker.apiGateways.elandReceiverDataFlush);a.style.width="0px";a.style.height="0px";a.style.border="0px";a.style.display="none";a.setAttribute("alt","elandTracker");a.setAttribute("title","elandTracker");document.body?document.body.appendChild(a):document.head&&document.head.appendChild(a)},1E3)};
ElandTracker.SendError=function(a){navigator&&navigator.userAgent&&(a=a+' ("'+navigator.userAgent+'")');var d=document.createElement("iframe"),f=ElandTracker.apiGateways.elandReceiverView;a="DMP_SR\x3deland-rd4\x26target\x3ddebug\x26error_message\x3d"+a;location&&location.origin&&location.pathname&&(a=a+"\x26url\x3d"+encodeURIComponent(location.origin+location.pathname));d.setAttribute("src",f+a);d.style.width="0px";d.style.height="0px";d.style.border="0px";d.style.display="none";d.setAttribute("alt",
"elandTracker");d.setAttribute("title","elandTracker");document.body?document.body.appendChild(d):document.head&&document.head.appendChild(d)};ElandTracker.ready&&ElandTracker.ready();